version: "4.3"

services:
    portal_fe-app:
        build:
            context: "."
        container_name: portal_fe-app
        ports:
            - 8085:5173
        networks:
            backend:
                aliases:
                    - app

networks:
    backend:
        name: portal_fe-network